parent: $LVSR/exp/wsj/configs/wsj_jan_new.yaml
net:
    dims_bidir: [17, 17, 17]
    subsample: [1, 2, 2]
    dim_dec: 19
    attention_type: content_and_conv
    conv_n: 13
    dec_stack: 2
    prior:
        before: 150
        after: 150
