parent: $LVSR/exp/wsj/configs/wsj_good_fbank.yaml
net:
    dims_bidir: [250, 500, 1000]
    subsample: [1, 2, 2]
    post_merge_dims: [1000]
    post_merge_activation: !!python/object/apply:blocks.bricks.Rectifier []
    # 0.25 times respective settings from wsj_good_fbank.yaml
    prior:
        before: 200
        after: 200
        initial_begin: 0
        initial_end: 40
        min_speed: 1.2
        max_speed: 2.1

