parent: $LVSR/exp/wsj/configs/wsj_paper1.yaml
net:
    dims_bidir: [250, 250, 250, 250]
    subsample: [1, 1, 1, 2]
    prior:
        before: 200
        after: 200
        type: window_around_median
stages:
    pretraining:
        net:
            prior:
                type: expanding
                initial_begin: 0
                initial_end: 80
                min_speed: 2.4
                max_speed: 4.4
