parent: $LVSR/exp/wsj/configs/wsj_jan_baseline.yaml
net:
    dims_bidir: [250, 250, 250, 250]
    subsample: [1, 1, 2, 2]
    dims_bottom: []
    prior:
        before: 100
        after: 100
        type: window_around_median
regularization:
    max_norm: 1.0
stages:
    pretraining:
        number: 0
        net:
            prior:
                type: expanding
                initial_begin: 0
                initial_end: 40
                min_speed: 1.2
                max_speed: 2.2
        training:
            num_epochs: 1
    main:
        number: 100
        training:
            restart_from: _best_ll
    annealing1:
        number: 200
        training:
            epsilon: 1.0e-10
            restart_from: _best_ll
    annealing2:
        number: 300
        training:
            epsilon: 1.0e-12
            restart_from: _best_ll
