parent: $LVSR/exp/wsj/configs/wsj_jan_new.yaml
net:
    bottom_activation: !!python/object/apply:blocks.bricks.Rectifier []
    dims_bottom: []

    enc_transition: !!python/name:blocks.bricks.recurrent.GatedRecurrent
    dims_bidir: [256, 256, 256, 256, 256, 256]
    subsample: [1, 1, 2, 2, 2, 2]

    prior: #essentially no prior!
      type: expanding
      initial_begin: 0
      initial_end: 10000
      max_speed: 0
      min_speed: 0
